#!/bin/bash
if [ ! -d "build" ] || [ ! -f "init" ]; then
  echo -e "\033[0;31mThis script must be executed from the root project directory.\033[0m"
  exit 1
fi

mkdir log
mkdir temp

composer install
bower install
npm install

echo -n "\033[0;31mDo you wish to do initial commit? y/n\033[0m "
read decision

case $decision in 
  [Yy]* )
    
  git remote rm origin  

  echo -n "Enter your GIT repository URL:";
  read origin_url

  git remote add origin "$origin_url"
  
  git rm "init"  
  git rm "README.md"
  git add .
  git commit -m '[clean initial environment]'
esac

rm "init"
rm "README.md"