#!/bin/bash


if [ ! -d "build" ] || [ ! -f "init" ]; then
  echo -e "\033[0;31mThis script must be executed from the root project directory.\033[0m"
  exit 1
fi

echo -n "Do you wish to install bower dependencies? y/n "
read decision

case $decision in 
  [Yy]* ) bower install;   
esac

echo -n "Do you wish to install npm packages? y/n "
read decision

case $decision in 
  [Yy]* ) npm install;   
esac

echo -n "Do you wish to do initial commit? y/n "
read decision

case $decision in 
  [Yy]* )
    
  git remote rm origin  

  echo -n "Enter your GIT repository URL:";
  read origin_url

  git remote add origin "$origin_url"

  rm "init"
  git rm "init"
  rm "README.md"
  git rm "README.md"
  git add .
  git commit -m '[clean initial environment]'
esac